//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rating_Comment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_platter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_platter()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int platter_id { get; set; }
        public string platter_name { get; set; }
        public string platter_description { get; set; }
        public byte[] platter_image { get; set; }
        public int platter_price { get; set; }
        public int Rest_id { get; set; }
        public int secret_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
